#docker-compose file for SQL Server

volumes:
  mssql_data:

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-sitiosapp
    restart: always
    ports:
      - "1433:1433"
    #user: "0"  # Cambia temporalmente a "0" (root) para evitar problemas de permisos en la restauración
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sql_Admin_2026!
    volumes:
      # ruta_host:ruta_contenedor
      - /var/opt/mssql/data:/var/opt/mssql/data
      - /var/opt/mssql/backup:/var/opt/mssql/backup # Aquí se guardar el .bak, validar con ruta en script .py de ser el caso
      - /var/opt/mssql/logs:/var/opt/mssql/logs
      - /var/opt/mssql/scripts:/var/opt/mssql/scripts # Aqui va el script de restauración